# Generated by Django 4.2 on 2024-10-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_full_name_userprofile_default_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_street_address',
            new_name='default_street_address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_full_name',
            new_name='full_name',
        ),
    ]
