# Generated by Django 4.2 on 2024-10-09 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_rename_default_street_address_userprofile_default_street_address1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='temporary_field',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_revenue',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='withdrawal_history',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('withdrawal_history', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
