# Generated by Django 4.2 on 2024-10-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_userprofile_temporary_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
