# Generated by Django 4.2 on 2024-10-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userprofile_total_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller_balance',
            new_name='balance',
        ),
    ]
