# Generated by Django 4.2 on 2024-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_historicalaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalaccount',
            name='history_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
