# Generated by Django 4.2 on 2024-11-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_rename_country_userprofile_default_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pending_payout',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='pending_payout',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
    ]
