# Generated by Django 4.2 on 2024-10-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_seller_balance'),
        ('products', '0006_alter_product_color_alter_product_fabric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
