# Generated by Django 4.2 on 2024-10-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_user_profile_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='return_unsold',
            new_name='return_option',
        ),
    ]
