# Generated by Django 4.2 on 2024-10-20 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_return_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='charge_for_unsold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
    ]
