# Generated by Django 4.2 on 2024-10-21 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
