# Generated by Django 4.2 on 2024-10-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_in_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
