# Generated by Django 4.2 on 2024-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_category_options_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='carbon_emission_per_kg',
            field=models.FloatField(default=0, help_text='carbonsave in kg'),
            preserve_default=False,
        ),
    ]
