# Generated by Django 4.2 on 2024-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_fabric_carbon_emission_per_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='carbon_emission_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
