# Generated by Django 4.2 on 2024-11-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_categories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_categories',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='products.category'),
        ),
    ]
