# Generated by Django 4.2 on 2024-11-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_category_options_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
