# Generated by Django 4.2 on 2024-11-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_product_listed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='listed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
       
    ]
